### ISSUE TITLE
Starting ventilation for a new patient

### ISSUE THREAD

**Issue by AmelMammar** [foselab/abz2024_casestudy_MLV#14]
Is it acceptable to start ventilation for a new patient without setting the desired parameters for that patient? According to Figure 3.1, it is possible. That means  ventilation will be performed with default values ?

**Comment by silviabonfanti** [comment]
Yes, it is possible. In case no parameters are set by physician, the ventilation is performed with default values.

**Comment by AmelMammar** [comment]
But some parameters (PEEP, FiO2, ...) do not have default values. Does this mean that any value (belonging to the range) can be chosen in the StartUp mode ?

**Comment by silviabonfanti** [comment]
PEEP and FiO2 do not have default values, because they are physical devices and it is not necessary to set them by the GUI. 
If the physician needs a different PEEP, he/she rotates a knob, on the physical valve, that can be adjusted by hand to a desired value. While for the FiO2 value, the physician turns the dial on the medical gas blender to set the desired FiO2.

**Comment by garganti** [comment]
> Yes, it is possible. In case no parameters are set by physician, the ventilation is performed with default values.

or the last set values - we ere told that often the doctors prefer to start the ventilation immediately, and only then they modify the parameters
